version: "3.9"

services:
  {{.Name}}:
    build: .
    container_name: {{.Name}}
    restart: always
    ports:
      - "0.0.0.0:{{.Port}}:{{.ToPort}}"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
