version: "3.9"

services:
  {{.Name}}:
    build: .
    container_name: {{.Name}}
    restart: always
    ports:
      - "0.0.0.0:{{.Port}}:{{.ToPort}}"
    networks:
      - mysql_dokploy-db   # attach service to network

networks:
  mysql_dokploy-db:
    driver: bridge
